service: self-decision-service

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  environment:
    REGION: us-east-2
    REQUEST_QUEUE_URL: http://localhost:4566/000000000000/self-decision-request-queue
    RESPONSE_QUEUE_URL: http://localhost:4566/000000000000/self-decision-response-queue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:SendMessage
      Resource: "*"

functions:
  notificationLambda:
    handler: dist/infrastructure/entrypoints/lambda/lambda.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - RequestQueue
              - Arn

resources:
  Resources:
    RequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: decision-request-queue

    ResponseQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: decision-response-queue

package:
  individually: true
  patterns:
    - '!test/**'
    - '!src/**'
    - '!coverage/**'
    - '!*.md'
    - '!tsconfig.json'
    - '!jest.config.js'
